### ISSUE TITLE
I made a fork...

### ISSUE THREAD

**Issue by budRich** [rosshemsley/iOpener#39]
Very nice to see that this excellent plugin is being maintained again.
I have been using my own personal modification of this for a long time, and recently thought i make a proper release of it. I didn't know about the new maintenance of this plugin when i started tidying up my own. 

I restructured the files and stuff quite a bit, so it isn't possible to make PR to this repo as it is now.
One thing, i made now, that i kind of regret is that i modernized the code to use `import typing` and statically typed the whole thing, so now it doesn't work on ST3 and below...

The main advantage with my fork is that it separates the tabcompletion into its own module, then i made two separate "command modules" PathBoxOpen (more or less same functionality as iOpener), and PathBoxMove which let you move and rename files with the same tabcompletion UI. This structure also makes it super easy to add more commands that would like to use the same UI.

If there is interest I could try porting the PathBoxMove functionality into a PR compatible with this repo.

https://github.com/budlime/PathBox

I have not submitted my version to PackageControl, thought i talk with you guys first.

**Comment by stoivo** [comment]
5 year ago I submitted my first pullrequest to this project. Nothing happend until very recently. rosshemsley added be as contibuter without any furher message. I dont plan on rewriting much here. IOpener is working. I don't realy know the codebase, and find it bit tangel together. I woudl probably only fix a bug here and there if something critical comes up.

So I think you have done a smart decission to start a new project and reimplement the features you want. IOpener also has some strange features so when  you start a new package dont need to carry that leagcy. I don't think you should regret "modernized the code" the code.
I think you could go ahead and release you package to on packagecontrol.io. Just so you know, would will get more issues then contribution. I cloned PathBox to try it out. I noticed that you have fixed some bugs already I have with iOperner I don't want to look into, related to tab completion. I wouldn't bind  `f2` automaticly just make it easy to add to keybinings.

I dont know rosshemsley so can't speak for him. I think we whould be fine with you releasing a new package. 

Sorry for taking a while to reply. Have a great weekend. havewa 👋 Simon

**Comment by budRich** [comment]
Thanks for the reply!
My thought regarding `F2` was to stay with the *theme* as iOpener brutally remaps `ctrl+o` ;) But I guess you are right since, ctrl+o/iOpener are interchangeable function wise. Where PathBoxMove and F2 isn't (im not even sure what the default behavior of F2 is).

I will try getting it into package control, Have a great weekend you too! // bud
